syntax = "proto3";

option csharp_namespace = "AnalisePrevGrpc";

service AnalisePrevService {

rpc Analisar (AnalisarRequest)
      returns (AnalisarResponse);

  rpc DetetarPol (PolRequest)
      returns (PolResponse);

  rpc PrevRisco (RiscoRequest)
      returns (RiscoResponse);

}

message AnalisarRequest {
    string type  = 1;
    string value = 2;
    string zona  = 3;
    string min   = 4;
    string max   = 5;
    string media = 6;
}

message AnalisarResponse {
    bool   valido   = 1;
    string nivel    = 2;
    string mensagem = 3;
    string erro     = 4;
}

message PolRequest {
    string zona  = 1;
    string pm25  = 2;
    string pm10  = 3;
    string ar    = 4;
}

message PolResponse {
    string mensagem = 1;
}

message RiscoRequest {
    string zona  = 1;
    string temp  = 2;
    string hum   = 3;
    string pm25  = 4;
    string ar    = 5;
}

message RiscoResponse {
    string mensagem = 1;
}